
//ฑ๊สถ   __WS_HOME_SAFE__  


SH_LIGHT_TIMER_ID,
SH_REBOOT_TIMER_ID,
SH_IN_IDLE_TIMER_ID,
#if defined(__MSGCMD_SUPPORT__)
MSGCMD_TIMER_BASE,
MSGCMD_TIMER_END = MSGCMD_TIMER_BASE+20,
#endif

